name: sixsigma-attrition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=23.0
  
  # Core Data Science
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.7.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.13.0
  
  # Statistical Analysis
  - scipy>=1.10.0
  - statsmodels>=0.14.0
  
  # Jupyter
  - notebook>=7.0.0
  - ipykernel>=6.25.0
  
  # Additional packages via pip
  - pip:
    - imbalanced-learn>=0.11.0
    - shap>=0.45.0
    - river>=0.21.0
    - joblib>=1.3.0